name: Publish Binaries

on:
  release:
    types:
      - published

jobs:
  publish-binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve artifacts
        run: |
          mkdir -p ./artifacts
          docker create --name amd64 linuxserver/docker-compose:amd64-${{ github.event.release.tag_name }}
          docker cp amd64:/usr/local/bin/docker ./artifacts/docker-cli-amd64
          docker create --name armhf linuxserver/docker-compose:arm32v7-${{ github.event.release.tag_name }}
          docker cp armhf:/usr/local/bin/docker ./artifacts/docker-cli-armhf
          docker create --name arm64 linuxserver/docker-compose:arm64v8-${{ github.event.release.tag_name }}
          docker cp arm64:/usr/local/bin/docker ./artifacts/docker-cli-arm64
      - name: Copy build-artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./artifacts/*"